$Version = "0.1"
$FPSName = "ModBootStrap"
$UtilVersionList = Invoke-RestMethod "https://raw.githubusercontent.com/MrFlufficans/DK2ModderUtilities/master/UtilVersion"
$VersionLine = ($UtilVersionList).split([Environment]::NewLine) | Select-String -Pattern "$FPSName" -SimpleMatch
$VersionLine = $VersionLine.ToString()
$VersionMaster = $VersionLine.SubString(($VersionLine.Length) -3)

$FluffyUtils = "
   ______     ______       __  ____  _ __
  / __/ /_ __/ _/ _/_ __  / / / / /_(_) /__
 / _// / // / _/ _/ // / / /_/ / __/ / (_-<
/_/ /_/\_,_/_//_/ \_, /  \____/\__/_/_/___/
                 /___/
"

Write-Host $FluffyUtils
Write-Host "   You Are Running $FPSName v$Version"
Write-Host "   Hosted On Github.com/MrFlufficans"
if ($VersionMaster -gt $Version) {
    Write-Host "`n  There is a New Version Available v$VersionMaster`n        Would you Like to Update?"
    $ConfirmUpdate = Read-Host "`t`t"
    $ConfirmUpdate = ($ConfirmUpdate.ToLower()).ToString()
    If ($ConfirmUpdate -match '^y(es)?$') {
        $Update = 1
    } else {
        $Update = 0
    }
} else {$Update = 0}

Start-Sleep 1

If ($Update) {
    Write-Host "`nFetching Update"
    $NewVersion = Invoke-RestMethod "https://raw.githubusercontent.com/MrFlufficans/DK2ModderUtilities/master/$FPSName.ps1"
    Start-Sleep 1
    If (Test-Path -Path ".\$FPSName.ps1" -PathType Leaf) {Clear-Content ".\$FPSName.ps1"}
    $NewVersion >> "$FPSName.ps1"
    Write-Host "Script Updated"
    Start-Sleep 1
    Write-Host "Relaunching in 3"
    Start-Sleep 1
    Write-Host "Relaunching in 2"
    Start-Sleep 1
    Write-Host "Relaunching in 1"
    Start-Sleep 1
    Start-Process powershell ".\$FPSName.ps1"
    Exit
} else {}


#Everything Above is just the Auto Update
#Actual Script Below Here

Write-Host "`n`n   What is the Name of your New Mod?"
$ModName = Read-Host "`t`t"
Start-Sleep 1
Write-Host "`n`n    What is the Mod Author's Name?"
$AuthorName = Read-Host "`t`t"
Start-Sleep 1
Write-Host "`n`n      Write a Short Description"
$ModDescription = Read-Host "`t"

$NewModPath = "$env:LOCALAPPDATA\KillHouseGames\DoorKickers2\Mods\$ModName"
$NewModxml = "<!--
This was Autogenerated using $FPSName $Version
-->
<Mod
    title=""$ModName""
    description=""$ModDescription""
    image=""""
    author=""$AuthorName""
    tags=""""
    changeNotes=""""
    languageMod=""""
    gameVersion=""30""
/>
"
New-Item -Path "$NewModPath" -ItemType Directory -Force | Out-Null
#New-Item -Path "$NewModPath\mod.xml" -ItemType file -Force
#$NewModxml | out-file -filepath "$NewModPath\mod.xml"
$NewModxml | Set-Content -Encoding UTF8 "$NewModPath\mod.xml"
cmd /c pause | out-null
